Call proper Bcg729 functions to release memory
arkadijs/asterisk-g72x pull request #3
Opened 2024-10-11 12:24 UTC by JoseGoncalves

When using `Bcg729` we need to call `closeBcg729EncoderChannel()` when encoding and `closeBcg729DecoderChannel()` when decoding.

2024-10-11 13:24 UTC, arkadijs requested changes
LGTM but please rename `g72x_destroy()` to match the content.

2024-10-11 13:46 UTC, JoseGoncalves commented
> LGTM but please rename `g72x_destroy()` to match the content.

Any suggestion for that function name?

2024-10-11 19:01 UTC, arkadijs commented
Naming is hard; `g72x_print_debug_on_destroy()`?

2024-10-12 08:51 UTC, arkadijs approved these changes

2024-10-12 08:52 UTC, merged

2024-10-12 08:52 UTC, arkadijs commented
Thank you for fixing the memory leak.